routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/','HomeController@index')->name('home.index');
// Route::get('/login','Auth\\LoginController@showLoginForm')->name('home.auth.login');
// Route::post('/login','Auth\\LoginController@login')->name('home.auth.login');
// Route::get('/logout','Auth\\LoginController@logout')->name('home.auth.logout');

// Route::get('/contact','HomeController@contact')->name('home.contact');
// Route::get('/akademik','HomeController@akademik')->name('home.akademik');

// Route::get('/{id}/show','HomeController@show')->name('home.show');
// Route::post('/store','HomeController@store')->name('home.store');

Route::group(['namespace' => 'Admin','prefix' => 'admin'],function(){
    //auth login
    Route::get('/','Auth\\LoginController@showLoginForm')->name('admin.auth');
    Route::get('/login','Auth\\LoginController@showLoginForm')->name('admin.auth.login');
    Route::post('/login','Auth\\LoginController@login')->name('admin.auth.login');
    Route::get('/logout','Auth\\LoginController@logout')->name('admin.auth.logout');

    Route::middleware('auth:admin')->group(function(){
        Route::get('/dashboard','DashboardController@index')->name('dashboard.index');    
    
        // Route::get('//pegawai','PegawaiController@index')->name('admin_pegawai_index');
        Route::get('/user/profile','UserController@profile')->name('user.profile');
        Route::resources([
            '/user' => 'UserController'
        ]);

       
        Route::get('/master_kelas/{id}/create_jadwal','MasterKelasController@createJadwal')->name('master_kelas.createJadwal');
        Route::get('/master_kelas/{id}/edit_jadwal','MasterKelasController@editJadwal')->name('master_kelas.editJadwal');
        Route::get('/master_kelas/{id}/delete_jadwal','MasterKelasController@deleteJadwal')->name('master_kelas.deleteJadwal');
        Route::put('/master_kelas/{id}/update_jadwal','MasterKelasController@updateJadwal')->name('master_kelas.updateJadwal');
        Route::post('/master_kelas/store_jadwal','MasterKelasController@storeJadwal')->name('master_kelas.storeJadwal');

        Route::get('/master_kelas/{id}/create_murid','MasterKelasController@createMurid')->name('master_kelas.createMurid');
        Route::get('/master_kelas/{id}/edit_murid','MasterKelasController@editMurid')->name('master_kelas.editMurid');
        Route::get('/master_kelas/{id}/delete_murid','MasterKelasController@deleteMurid')->name('master_kelas.deleteMurid');
        Route::put('/master_kelas/{id}/update_murid','MasterKelasController@updateMurid')->name('master_kelas.updateMurid');
        Route::post('/master_kelas/store_murid','MasterKelasController@storeMurid')->name('master_kelas.storeMurid');

        
        
        
       

        Route::get('/proposal/{id}/print','ProposalController@print')->name('proposal.print');
        Route::resources([
            '/proposal' => 'ProposalController'
        ]);
        
        Route::get('/jadwal/print','JadwalController@print')->name('jadwal.print');
        Route::resources([
            '/jadwal' => 'JadwalController'
        ]);

        Route::resources([
            '/jadwal_radio' => 'JadwalRadioController'
        ]);
        Route::get('/jadwal_radio/{id}/createUser','JadwalRadioController@createUser')->name('jadwal_radio.createUser');
        Route::get('/jadwal_radio/{id}/createKehadiran','JadwalRadioController@createKehadiran')->name('jadwal_radio.createKehadiran');
        Route::get('/jadwal_radio/{id}/editKehadiran','JadwalRadioController@editKehadiran')->name('jadwal_radio.editKehadiran');
        Route::get('/jadwal_radio/{id}/deleteUser','JadwalRadioController@deleteUser')->name('jadwal_radio.deleteUser');
        Route::get('/jadwal_radio/{id}/print','JadwalRadioController@print')->name('jadwal_radio.print');
        Route::post('/jadwal_radio/{id}/storeUser','JadwalRadioController@storeUser')->name('jadwal_radio.storeUser');
        Route::post('/jadwal_radio/{id}/storeKehadiran','JadwalRadioController@storeKehadiran')->name('jadwal_radio.storeKehadiran');
        Route::put('/jadwal_radio/{id}/updateKehadiran','JadwalRadioController@updateKehadiran')->name('jadwal_radio.updateKehadiran');
        Route::get('/jadwal_radio/{id}/showKehadiran','JadwalRadioController@showKehadiran')->name('jadwal_radio.showKehadiran');

        Route::resources([
            '/bidang' => 'BidangController'
        ]);


        Route::resources([
            '/iuran' => 'IuranController'
        ]);
        Route::get('/iuran/{id}/delete','IuranController@delete')->name('iuran.delete');

        Route::get('/kehadiran/{id}/index','KehadiranController@index')->name('kehadiran.index');
        Route::get('/kehadiran/{id}/create','KehadiranController@create')->name('kehadiran.create');
        Route::get('/kehadiran/{id}/edit','KehadiranController@edit')->name('kehadiran.edit');
        Route::post('/kehadiran/store','KehadiranController@store')->name('kehadiran.store');
        Route::put('/kehadiran/{id}/update','KehadiranController@update')->name('kehadiran.update');
        Route::get('/kehadiran/{id}/show','KehadiranController@show')->name('kehadiran.show');

        
       

        Route::resources([
            '/properti' => 'PropertiController'
        ]);
        Route::get('/properti/{id}/create_foto','PropertiController@createFoto')->name('properti.createFoto');
        Route::post('/properti/storeFoto','PropertiController@storeFoto')->name('properti.storeFoto');
        Route::get('/properti/{id}/deleteFoto','PropertiController@deleteFoto')->name('properti.deleteFoto');
        
    });
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ADMIN</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/select2/dist/css/select2.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/Ionicons/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/morris.js/morris.css">
    
    
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="{{asset('admin-lte')}}/https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b></b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">                        
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{asset('image/logo_itt.jpg')}}" class="user-image" alt="User Image">
                                <span class="hidden-xs"> {{Auth::guard('admin')->user()->role}}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="{{asset('image/logo_itt.jpg')}}" class="img-circle" alt="User Image">

                                    <p>
                                        {{Auth::guard('admin')->user()->nama}}                                       
                                    </p>
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{{route('user.profile')}}" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{route('admin.auth.logout')}}" class="btn btn-default btn-flat">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="{{asset('image/logo_itt.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>{{Auth::guard('admin')->user()->nama}}</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>  
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="">
                        <a href="{{route('dashboard.index')}}">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>                            
                        </a>                        
                    </li>

                   

                    @if(AppHelper::access(['Kordinator','Anggota','Admin']))
                        <li class="{{$template->menu == 'proposal' ? 'active' : ''}}">
                            <a href="{{route('proposal.index')}}"  >
                                <i class="fa fa-file"></i> 
                                <span>Proposal</span>
                            </a>
                        </li>   
                    @endif 
                      

                     @if(AppHelper::access(['Kordinator','Anggota', 'Admin']))
                        <li class="{{$template->menu == 'jadwal' ? 'active' : ''}}">
                            <a href="{{route('jadwal.index')}}"  >
                                <i class="fa fa-calendar"></i> 
                                <span>Jadwal MC</span>
                            </a>
                        </li>   
                    @endif 
                    
                    @if(AppHelper::access(['Kordinator','Anggota','Admin']))
                        <li class="{{$template->menu == 'jadwal_radio' ? 'active' : ''}}">
                            <a href="{{route('jadwal_radio.index')}}"  >
                                <i class="fa fa-calendar"></i> 
                                <span>Jadwal Radio</span>
                            </a>
                        </li>   
                    @endif

                    {{-- //menentukan hak akses user --}}
                    @if(AppHelper::access(['Admin']))
                        <li class="{{$template->menu == 'bidang' ? 'active' : ''}}">
                            <a href="{{route('bidang.index')}}"  >
                                <i class="fa fa-tags"></i> 
                                <span>Bidang</span>
                            </a>
                        </li>   
                    @endif  
                    
                   
                    
                    {{-- //menentukan hak akses user --}}
                    @if(AppHelper::access(['Admin','Kordinator']))
                        <li class="{{$template->menu == 'user' ? 'active' : ''}}">
                            <a href="{{route('user.index')}}"  >
                                <i class="fa fa-users"></i> 
                                <span>Manajemen Anggota</span>
                            </a>
                        </li>   
                    @endif                     
                    
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        @yield('content')
        
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; 2018 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
            reserved.
        </footer>
        
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->

    <!-- jQuery 3 -->
    <script src="{{asset('admin-lte')}}/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{{asset('admin-lte')}}/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{asset('admin-lte')}}/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="{{asset('admin-lte')}}/bower_components/raphael/raphael.min.js"></script>
    <script src="{{asset('admin-lte')}}/bower_components/morris.js/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="{{asset('admin-lte')}}/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="{{asset('admin-lte')}}/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="{{asset('admin-lte')}}/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{asset('admin-lte')}}/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="{{asset('admin-lte')}}/bower_components/moment/min/moment.min.js"></script>
    <script src="{{asset('admin-lte')}}/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="{{asset('admin-lte')}}/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{{asset('admin-lte')}}/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- DataTables -->
    <script src="{{asset('admin-lte')}}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('admin-lte')}}/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <!-- Slimscroll -->
    <script src="{{asset('admin-lte')}}/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="{{asset('admin-lte')}}/bower_components/fastclick/lib/fastclick.js"></script>
    {{-- select2 --}}
    <script src="{{asset('admin-lte')}}/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('admin-lte')}}/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('admin-lte')}}/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{asset('admin-lte')}}/dist/js/demo.js"></script>
    <!-- CK Editor -->
    <script src="{{asset('admin-lte')}}/bower_components/ckeditor/ckeditor.js"></script>
    <script>
        //Date picker
        $('.datepicker').datepicker({
            autoclose: true,
            format : 'yyyy-mm-dd'
        })

        $('.select2').select2();

        // Replace the <textarea id="ckeditor"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replaceClass('ckeditor')
        
    </script>
    @stack('js')
</body>

</html>